name = "adtracktiv-proxy"
main = "src/worker.js"
compatibility_date = "2024-04-09"

services = [
  { binding = "ROUTER", service = "cloudflare-tracking-router" }
]

kv_namespaces = [
    { binding = "SDK_CONFIG", id = "567f9098e474460695a647ef4e1baae4" }
]

[vars]
DATABASE_URL = "postgres://default:YARjpaN2hKT4@ep-blue-star-a44wwese-pooler.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require"

