name = "adtracktiv-proxy"
main = "src/worker.js"
compatibility_date = "2024-04-09"
workers_dev = true

[vars]
DATABASE_URL = "postgresql://test-db_owner:RuJjb6cYPZ5p@ep-divine-bird-a14u7eh7-pooler.ap-southeast-1.aws.neon.tech/test-db?sslmode=require"